version: "3.8"

services:
  backend:
    container_name: rails-backend  
    build:
      context: ./hello_app
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "3000:3000"
    volumes:
      - ./hello_app:/rails