require "test_helper"


# The helper method static_pages_home_url is not explicitly defined by you, but it's automatically generated by Rails based on your route definitions. This is part of Rails' convention over configuration principle.

# Here's how it works:

# When you define a route in your config/routes.rb file, like this:
# ruby
# CopyInsert
# get 'static_pages/home'
# Rails automatically generates several helper methods, including:
# static_pages_home_path (returns the path portion of the URL)
# static_pages_home_url (returns the full URL including protocol and host)

class StaticPagesControllerTest < ActionDispatch::IntegrationTest

  def setup
    @base_title = "Ruby on Rails Tutorial Sample App"
  end

  test "should get root" do
    get root_path
    assert_response :success
  end

  test "should get home" do
    get root_path
    assert_response :success
    assert_select "title", "Home | #{@base_title}"
  end

  test "should get help" do
    get help_path
    assert_response :success
    assert_select "title", "Help | #{@base_title}"
  end

  test "should get about" do
    get about_path
    assert_response :success
    assert_select "title", "About | #{@base_title}"
  end

  test "should get contact" do
    get contact_path
    assert_response :success
    assert_select "title", "Contact | #{@base_title}"
  end
end